services:
  # Add a healthcheck to MySQL so we only proceed once it's ready
  db:
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$${MYSQL_ROOT_PASSWORD} || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s

  # One-off curl container attached to the same network; it will hit nginx by service name
  curl:
    image: curlimages/curl:8.10.1
    depends_on:
      - nginx
    networks: [todo-net]
    # retry a bunch while app/nginx settle; -f = fail on HTTP >=400, -sS = quiet + show errors
    command: ["--retry", "20", "--retry-delay", "2", "-fsS", "http://nginx:80/"]
